# Generated by Django 5.1.7 on 2025-03-08 09:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_add_1000_products"),
        ("shop", "0003_order"),
    ]

    operations = []
