# Generated by Django 5.1.7 on 2025-03-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_merge_0003_add_1000_products_0003_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
